### ISSUE TITLE
quiz-score

### ISSUE THREAD

**Issue by ThomasShelBy2105175** [SamyoPramanik/LearnSphere#7]
CREATE OR REPLACE FUNCTION QUIZ_SCORE_STUDENT(INPUT_ID IN INTEGER, INPUT_COURSEID IN INTEGER)
RETURN INTEGER IS
    TSCORE INTEGER;
		TEMP_SCORE INTEGER;
		TEMP_ANSWER INTEGER:=0;
		ORIGINAL_ANSWER INTEGER:=0;
		TEMP_QUESID INTEGER:=0;
BEGIN
    TSCORE:=0;
    FOR R IN (SELECT ID 
		          FROM QUIZ_PARTICIPATION 
		          WHERE EXISTS(SELECT 1 FROM QUIZ Q WHERE Q.ID=QUIZ_ID AND COURSE_ID=INPUT_COURSEID) AND LEARNER_ID=INPUT_ID 
							ORDER BY TIME ASC
							FETCH FIRST 1 ROW ONLY)
		LOOP
				TEMP_SCORE:=0;
				BEGIN
						 --IF(R.SUBMITTED='TRUE') THEN									
										FOR P IN (SELECT QUESTION_ID, ANSWER FROM QUIZ_SUBMISSION WHERE PARTICIPATION_ID=R.ID)
										LOOP
											  ORIGINAL_ANSWER:=0;
											  BEGIN
												    SELECT ANSWER INTO ORIGINAL_ANSWER
													  FROM QB
														WHERE ID=P.QUESTION_ID;
																							
										        IF P.ANSWER=ORIGINAL_ANSWER THEN
												          TEMP_SCORE:=20;
										        ELSE
										              TEMP_SCORE:=-4;
										        END IF;
														TSCORE:=TSCORE+TEMP_SCORE;
												END;
									 END LOOP;							
					   --END IF;		 
				EXCEPTION
            WHEN NO_DATA_FOUND THEN
                DBMS_OUTPUT.PUT_LINE('NO DATA FOUND!');																												 
	      END;					 
		END LOOP;
		RETURN TSCORE;
END;

**Comment by ThomasShelBy2105175** [comment]
CREATE OR REPLACE FUNCTION QUIZ_SCORE_STUDENT(INPUT_ID IN INTEGER, INPUT_COURSEID IN INTEGER)
RETURN INTEGER IS
    TSCORE INTEGER;
		TEMP_SCORE INTEGER;
		TEMP_ANSWER INTEGER:=0;
		ORIGINAL_ANSWER INTEGER:=0;
		TEMP_QUESID INTEGER:=0;
BEGIN
    TSCORE:=0;
    FOR R IN (SELECT ID 
		          FROM QUIZ_PARTICIPATION 
		          WHERE EXISTS(SELECT 1 FROM QUIZ Q WHERE Q.ID=QUIZ_ID AND COURSE_ID=INPUT_COURSEID) AND LEARNER_ID=INPUT_ID 
							ORDER BY TIME ASC
							FETCH FIRST 1 ROW ONLY)
		LOOP
				TEMP_SCORE:=0;
				BEGIN
						 --IF(R.SUBMITTED='TRUE') THEN									
										FOR P IN (SELECT QUESTION_ID, ANSWER FROM QUIZ_SUBMISSION WHERE PARTICIPATION_ID=R.ID)
										LOOP
											  ORIGINAL_ANSWER:=0;
											  BEGIN
												    SELECT ANSWER INTO ORIGINAL_ANSWER
													  FROM QB
														WHERE ID=P.QUESTION_ID;
																							
										        IF P.ANSWER=ORIGINAL_ANSWER THEN
												          TEMP_SCORE:=20;
										        ELSE
										              TEMP_SCORE:=-4;
										        END IF;
														TSCORE:=TSCORE+TEMP_SCORE;
												END;
									 END LOOP;							
					   --END IF;		 
				EXCEPTION
            WHEN NO_DATA_FOUND THEN
                DBMS_OUTPUT.PUT_LINE('NO DATA FOUND!');																												 
	      END;					 
		END LOOP;
		RETURN TSCORE;
END;

**Comment by ThomasShelBy2105175** [comment]
CREATE OR REPLACE FUNCTION QUIZ_SCORE_STUDENT(INPUT_ID IN INTEGER, INPUT_COURSEID IN INTEGER)
RETURN INTEGER IS
    TSCORE INTEGER;
		TEMP_SCORE INTEGER;
		TEMP_ANSWER INTEGER:=0;
		ORIGINAL_ANSWER INTEGER:=0;
		TEMP_QUESID INTEGER:=0;
BEGIN
    TSCORE:=0;
    FOR R IN (SELECT ID 
		          FROM QUIZ_PARTICIPATION 
		          WHERE EXISTS(SELECT 1 FROM QUIZ Q WHERE Q.ID=QUIZ_ID AND COURSE_ID=INPUT_COURSEID) AND LEARNER_ID=INPUT_ID 
							ORDER BY TIME ASC
							FETCH FIRST 1 ROW ONLY)
		LOOP
				TEMP_SCORE:=0;
				BEGIN
						 --IF(R.SUBMITTED='TRUE') THEN									
										FOR P IN (SELECT QUESTION_ID, ANSWER FROM QUIZ_SUBMISSION WHERE PARTICIPATION_ID=R.ID)
										LOOP
											  ORIGINAL_ANSWER:=0;
											  BEGIN
												    SELECT ANSWER INTO ORIGINAL_ANSWER
													  FROM QB
														WHERE ID=P.QUESTION_ID;
																							
										        IF P.ANSWER=ORIGINAL_ANSWER THEN
												          TEMP_SCORE:=20;
										        ELSE
										              TEMP_SCORE:=-4;
										        END IF;
														TSCORE:=TSCORE+TEMP_SCORE;
												END;
									 END LOOP;							
					   --END IF;		 
				EXCEPTION
            WHEN NO_DATA_FOUND THEN
                DBMS_OUTPUT.PUT_LINE('NO DATA FOUND!');																												 
	      END;					 
		END LOOP;
		RETURN TSCORE;
END;

**Comment by SamyoPramanik** [comment]
```sql
CREATE OR REPLACE FUNCTION QUIZ_SCORE_STUDENT(INPUT_ID IN INTEGER, INPUT_COURSEID IN INTEGER)
RETURN INTEGER IS
    TSCORE INTEGER;
		TEMP_SCORE INTEGER;
		TEMP_ANSWER INTEGER:=0;
		ORIGINAL_ANSWER INTEGER:=0;
		TEMP_QUESID INTEGER:=0;
BEGIN
    TSCORE:=0;
    FOR R IN (SELECT ID 
		          FROM QUIZ_PARTICIPATION 
		          WHERE EXISTS(SELECT 1 FROM QUIZ Q WHERE Q.ID=QUIZ_ID AND COURSE_ID=INPUT_COURSEID) AND LEARNER_ID=INPUT_ID 
							ORDER BY TIME ASC
							FETCH FIRST 1 ROW ONLY)
		LOOP
				TEMP_SCORE:=0;
				BEGIN
						 --IF(R.SUBMITTED='TRUE') THEN									
										FOR P IN (SELECT QUESTION_ID, ANSWER FROM QUIZ_SUBMISSION WHERE PARTICIPATION_ID=R.ID)
										LOOP
											  ORIGINAL_ANSWER:=0;
											  BEGIN
												    SELECT ANSWER INTO ORIGINAL_ANSWER
													  FROM QB
														WHERE ID=P.QUESTION_ID;
																							
										        IF P.ANSWER=ORIGINAL_ANSWER THEN
												          TEMP_SCORE:=20;
										        ELSE
										              TEMP_SCORE:=-4;
										        END IF;
														TSCORE:=TSCORE+TEMP_SCORE;
												END;
									 END LOOP;							
					   --END IF;		 
				EXCEPTION
            WHEN NO_DATA_FOUND THEN
                DBMS_OUTPUT.PUT_LINE('NO DATA FOUND!');																												 
	      END;					 
		END LOOP;
		RETURN TSCORE;
END;
```
